# Generated by Django 6.0.4 on 2026-09-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('cultura', models.CharField(max_length=80)),
                ('produtor', models.CharField(max_length=160)),
                ('geometria', models.JSONField(help_text='Geometria GeoJSON do talhão.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'talhão',
                'verbose_name_plural': 'talhões',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REVISAO', 'Revisão'), ('BLOQUEADO', 'Bloqueado')], default='REVISAO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='lavouras.talhao')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
